ContentController:
  extensions:
    - SeoHeroToolController
SiteTree:
  extensions:
    - SeoHeroToolDataObject
LeftAndMain:
  extra_requirements_css:
    - silverstripe-seo-hero-tool/css/SeoHeroTool.css
